@ECHO OFF

SET IS_USAGE=FALSE
IF "%1" == "/h" SET IS_USAGE=TRUE
IF "%1" == ""   SET IS_USAGE=TRUE
IF %IS_USAGE%==TRUE (
  ECHO usage: %0 [WSL_VER] [CUSTOM_DIST_NAME] [TAR_FILE_PATH] [INSTALL_LOCATION]
  EXIT /B
)

SET   WSL_VER=%1
SET DIST_NAME=%2
SET  TAR_FILE=%3
SET INST_LOCT=%4

IF NOT EXIST %INST_LOCT% MKDIR %INST_LOCT%

ECHO START IMPORT %DIST_NAME% TO %BACKUP_FULL_PATH%

wsl --import %DIST_NAME% %INST_LOCT% %TAR_FILE% --version %WSL_VER%

ECHO DONE!
